/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tower1(props) {
  const { nodes, materials } = useGLTF('/Test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0, 1]} />
    </group>
  )
}

useGLTF.preload('/Test.glb')
