/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tower1(props) {
  const { nodes, materials } = useGLTF('/Tower1.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/Tower1.gltf')
