const CHUNK_SIZE = 10;
const CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE;
const TILE_SIZE = 25;
const CHUNK_GEOMETRY = [CHUNK_SIZE, CHUNK_SIZE]

export {
    CHUNK_SIZE,
    CHUNK_AREA,
    TILE_SIZE,
    CHUNK_GEOMETRY
}