/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import get from 'lodash/get';
import compact from 'lodash/compact';

// entity dispatch events
import { SELECT_ENTITY, HOVER_ENTITY_START, HOVER_ENTITY_STOP } from '../../../reducers/entityReducer';

export function GLTFModel(props) {
  const { entity, entityReducer, action, actionEffectMutation, gltfPath } = props;
  const { materialMap }= entity;
  const { position } = props;
  // const { color, position, rotation, id, scale } = entity;
  const { entityState, entityDispatch } = entityReducer;

  const ref = useRef();
  const [hovered, hover] = useState(false);
  const { nodes, materials } = useGLTF(gltfPath); // useGLTF('/TestHuman.gltf');
  
  // <mesh geometry={nodes.Cube.geometry} material={materials.Material} color={props.color} >s
  useFrame((state, delta) => {
    if (entity.tic) entity.tic(ref, delta, entityReducer, actionEffectMutation);
  });
  return (
    <Suspense fallback={null}>
      <group {...props} position={position} key={entity.id} dispose={null}
        ref={ref}
        onClick={(event) => {
          // um this doesn't seem to work... Something else is selecting entities, and it doesn'tseem to use entityDispatch(SELECT_ENTITY)
          //console.log('gltfModel onclick action', action)
          if (action) return;
          // console.log('gltfModel onclick selectedUnits.length', entityState.selectedUnits.length)
          // console.log('gltfModel onclick selectedUnits[0]', entityState.selectedUnits[0])
          // console.log('entity', entity)
          if (entityState.selectedUnits.length && entityState.selectedUnits[0].id === entity.id) return;
          // console.log('about to call dispatch')
          entityDispatch({ 
            type: SELECT_ENTITY,
            payload: [entity] 
          }) 
        }}
        onPointerOver={(event) => {
          if (action) return;
          hover(true);
          entityDispatch({
            type: HOVER_ENTITY_START,
            payload: entity
          });
        }}
        onPointerOut={(event) => {
          if (action) return;
          hover(false)
          entityDispatch({
            type: HOVER_ENTITY_STOP,
            payload: entity
          });
        }}
        >
          {
            compact(Object.entries(nodes).map(([key, value]) => {
              if (key === 'Scene') return null;
              const geometry = get(nodes, `${key}.geometry`, null);
              const material = materials[`${materialMap(key)}`]; //.Material; // get(materials, materialMap(key), null);
              // console.log(`nodes.${key} geometry,`, geometry, ` materials.${materialMap(key)}`, material)
              // console.log(materials)
              return (
                <mesh 
                  key={`nodes.${key}`}
                  geometry={geometry}
                  material={material}
                  material-color={hovered ? 'white' : props.color}
                />);
              //return (<mesh geometry={nodes.Cube.geometry} material={materials.Material} material-color={hovered ? 'white' : props.color} />);
            }))
          }
          {/* material-color={hovered ? 'white' : props.color} */}
          {/* <meshStandardMaterial color={props.color} /> */}
        </group>
      </Suspense>
    
  )
}

// useGLTF.preload('/TestHuman.gltf')
