/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef, useState, Suspense } from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';
import get from 'lodash/get';
import compact from 'lodash/compact';

// entity dispatch events
import { SELECT_ENTITY, HOVER_ENTITY_START, HOVER_ENTITY_STOP } from '../../../reducers/entityReducer';

export function GLTFModel(props) {
  const { entity, entityReducer, action, actionEffectMutation, gltfPath } = props;
  const { materialMap }= entity;
  const { position } = props;
  // const { color, position, rotation, id, scale } = entity;
  const { entityState, entityDispatch } = entityReducer;

  const ref = useRef();
  const [hovered, hover] = useState(false);
  const { nodes, materials } = useGLTF(gltfPath);
  
  useFrame((state, delta) => {
    if (entity.tic) entity.tic(ref, delta, entityReducer, actionEffectMutation);
  });
  return (
    <Suspense fallback={null}>
      <group {...props} position={position} key={entity.id} dispose={null}
        ref={ref}
        onClick={(event) => {
          if (action) return;
          if (entityState.selectedUnits.length && entityState.selectedUnits[0].id === entity.id) return;
          entityDispatch({ 
            type: SELECT_ENTITY,
            payload: [entity] 
          }) 
        }}
        onPointerOver={(event) => {
          if (action) return;
          hover(true);
          entityDispatch({
            type: HOVER_ENTITY_START,
            payload: entity
          });
        }}
        onPointerOut={(event) => {
          if (action) return;
          hover(false)
          entityDispatch({
            type: HOVER_ENTITY_STOP,
            payload: entity
          });
        }}
        >
          {
            compact(Object.entries(nodes).map(([key, value]) => {
              if (key === 'Scene') return null;
              const geometry = get(nodes, `${key}.geometry`, null);
              const material = materials[`${materialMap(key)}`]; 
              return (
                <mesh 
                  key={`nodes.${key}`}
                  geometry={geometry}
                  material={material}
                  material-color={hovered ? 'white' : props.color}
                />);
            }))
          }
        </group>
      </Suspense>
    
  )
}
