/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TestHuman(props) {
  const { nodes, materials } = useGLTF('/TestHuman.gltf')
  // <mesh geometry={nodes.Cube.geometry} material={materials.Material} color={props.color} >s
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} color={props.color} >
        <meshStandardMaterial color={props.color} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/TestHuman.gltf')
